kind: pipeline
type: docker
name: build

steps:
- name: backend
  image: golang
  commands:
    - mkdir data
    - go get -u github.com/golang/dep/cmd/dep
    - dep ensure
    - go build -o mobile-node-remote-client .
    - chmod +x mobile-node-remote-client

- name: frontend
  image: node:6
  commands:
    - npm install
    - npm test

- name: publish
  image: plugins/docker
  settings:
    repo: octocat/hello-world
    tags: [ 1, 1.1, latest ]
    registry: index.docker.io

- name: notify
  image: plugins/slack
  settings:
    channel: developers
    username: drone
